name: BitcoinQuery Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        platform: [Any CPU]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

      - name: Install .NET Framework 4.8 with Chocolatey
        run: choco install netfx-4.8 -y

      - name: Install .NET Framework 4.0 Developer Pack with Chocolatey
        run: choco install netfx-4.0.1-devpack --ignore-checksums
        
      - name: Restore NuGet packages for solution
        run: nuget restore BitcoinQuery/BitcoinQuery.sln

      - name: Restore NuGet packages for BitcoinQuery.DesktopClient
        run: dotnet restore BitcoinQuery/BitcoinQuery.DesktopClient/BitcoinQuery.DesktopClient.csproj

      - name: Build BitcoinQuery.DesktopClient
        run: dotnet build BitcoinQuery/BitcoinQuery.DesktopClient/BitcoinQuery.DesktopClient.csproj --configuration Release

      - name: Restore NuGet packages for BitcoinQuery.DesktopClientUnitTests
        run: dotnet restore BitcoinQuery/BitcoinQuery.DesktopClientUnitTests/BitcoinQuery.DesktopClientUnitTests.csproj

      - name: Build BitcoinQuery.DesktopClientUnitTests
        run: dotnet build BitcoinQuery/BitcoinQuery.DesktopClientUnitTests/BitcoinQuery.DesktopClientUnitTests.csproj --configuration Release

      - name: Run BitcoinQuery.DesktopClientUnitTests
        run: dotnet test BitcoinQuery/BitcoinQuery.DesktopClientUnitTests/BitcoinQuery.DesktopClientUnitTests.csproj --configuration Release

      - name: Setup .NET 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.x'

      - name: Restore NuGet packages for BitcoinQuery.ServerSideUnitTests
        run: dotnet restore BitcoinQuery/BitcoinQuery.ServerSideUnitTests/BitcoinQuery.ServerSideUnitTests.csproj

      - name: Build BitcoinQuery.ServerSideUnitTests
        run: dotnet build BitcoinQuery.ServerSideUnitTests/BitcoinQuery.ServerSideUnitTests.csproj --configuration Release

      - name: Run BitcoinQuery.ServerSideUnitTests
        run: dotnet test BitcoinQuery/BitcoinQuery.ServerSideUnitTests/BitcoinQuery.ServerSideUnitTests.csproj --configuration Release

      - name: Restore NuGet packages for BitcoinQuery.Service
        run: dotnet restore BitcoinQuery/BitcoinQuery.Service/BitcoinQuery.Service.csproj

      - name: Build BitcoinQuery.Service
        run: dotnet build BitcoinQuery/BitcoinQuery.Service/BitcoinQuery.Service.csproj --configuration Release

      - name: Restore NuGet packages for BitcoinQuery.UnitTests
        run: dotnet restore BitcoinQuery/BitcoinQuery.UnitTests/BitcoinQuery.UnitTests.csproj

      - name: Build BitcoinQuery.UnitTests
        run: dotnet build BitcoinQuery/BitcoinQuery.UnitTests/BitcoinQuery.UnitTests.csproj --configuration Release

      - name: Run BitcoinQuery.UnitTests
        run: dotnet test BitcoinQuery/BitcoinQuery.UnitTests/BitcoinQuery.UnitTests.csproj --configuration Release

      - name: Restore NuGet packages for BitcoinQuery.WebGateway
        run: dotnet restore BitcoinQuery/BitcoinQuery.WebGateway/BitcoinQuery.WebGateway.csproj

      - name: Build BitcoinQuery.WebGateway
        run: dotnet build BitcoinQuery/BitcoinQuery.WebGateway/BitcoinQuery.WebGateway.csproj --configuration Release
