name: BitcoinQuery Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install .NET Framework 4.8.1 if needed
        run: |
          $netVersion = Get-ChildItem "HKLM:\SOFTWARE\Microsoft\NET Framework Setup\NDP" -ErrorAction SilentlyContinue | Get-ItemPropertyValue -Name Version -ErrorAction SilentlyContinue
          if ($netVersion -notcontains "v4.8.04084") {
            choco install netfx-4.8.1
            choco install netfx-4.8.1-devpack
          }

      - name: Build BitcoinQuery.DesktopClient
        run: dotnet build BitcoinQuery/BitcoinQuery.DesktopClient/BitcoinQuery.DesktopClient.csproj --configuration Release

      - name: Build BitcoinQuery.DesktopClientUnitTests
        run: dotnet build BitcoinQuery/BitcoinQuery.DesktopClientUnitTests/BitcoinQuery.DesktopClientUnitTests.csproj --configuration Release

      - name: Run BitcoinQuery.DesktopClientUnitTests
        run: dotnet test BitcoinQuery/BitcoinQuery.DesktopClientUnitTests/BitcoinQuery.DesktopClientUnitTests.csproj --configuration Release

      - name: Build BitcoinQuery.ServerSideUnitTests
        run: dotnet build BitcoinQuery.ServerSideUnitTests/BitcoinQuery.ServerSideUnitTests.csproj --configuration Release

      - name: Run BitcoinQuery.ServerSideUnitTests
        run: dotnet test BitcoinQuery/BitcoinQuery.ServerSideUnitTests/BitcoinQuery.ServerSideUnitTests.csproj --configuration Release

      - name: Build BitcoinQuery.Service
        run: dotnet build BitcoinQuery/BitcoinQuery.Service/BitcoinQuery.Service.csproj --configuration Release

      - name: Build BitcoinQuery.UnitTests
        run: dotnet build BitcoinQuery/BitcoinQuery.UnitTests/BitcoinQuery.UnitTests.csproj --configuration Release

      - name: Run BitcoinQuery.UnitTests
        run: dotnet test BitcoinQuery/BitcoinQuery.UnitTests/BitcoinQuery.UnitTests.csproj --configuration Release

      - name: Build BitcoinQuery.WebGateway
        run: dotnet build BitcoinQuery/BitcoinQuery.WebGateway/BitcoinQuery.WebGateway.csproj --configuration Release
